import { csvEuro, toCsv } from './csv';
import { formatDateTime, hhmm } from './format';
import { OCCASION_LABEL, PAYMENT_LABEL, STATUS_LABEL, type Booking } from './types';

const HEADER = [
  'Buchungscode',
  'Datum',
  'Beginn',
  'Ende',
  'Status',
  'Quelle',
  'Zahlungsart',
  'Vorname',
  'Nachname',
  'E-Mail',
  'Telefon',
  'Personen',
  'Anlass',
  'Firma',
  'USt-ID',
  'Rechnung gewünscht',
  'Straße',
  'PLZ',
  'Ort',
  'Wünsche',
  'Newsletter',
  'Gesamt €',
  'Lounge €',
  'Gebühr €',
  'Händler-Anteil €',
  'In Abrechnung',
  'Bezahlt am',
  'Eingecheckt',
  'Taler übergeben',
  'Storniert am',
  'Storno-Grund',
];

/** Buchungsexport (Admin): alle Felder, Beträge als Excel-Zahl. */
export function bookingsCsv(rows: Booking[]): string {
  return toCsv(
    HEADER,
    rows.map((b) => [
      b.booking_code,
      b.date.split('-').reverse().join('.'),
      hhmm(b.start_time),
      hhmm(b.end_time),
      STATUS_LABEL[b.status],
      b.source === 'manual' ? 'manuell' : 'online',
      PAYMENT_LABEL[b.payment_method],
      b.first_name,
      b.last_name,
      b.email,
      b.phone,
      b.persons,
      b.occasion ? (OCCASION_LABEL[b.occasion] ?? b.occasion) : '',
      b.company_name,
      b.vat_id,
      b.invoice_requested ? 'ja' : 'nein',
      b.billing_street,
      b.billing_zip,
      b.billing_city,
      b.notes,
      b.newsletter_opt_in ? 'ja' : 'nein',
      csvEuro(b.amount_total_cents),
      csvEuro(b.price_cents),
      csvEuro(b.fee_cents),
      csvEuro(b.include_in_settlement && b.status === 'paid' ? b.haendler_share_cents : 0),
      b.include_in_settlement ? 'ja' : 'nein',
      b.paid_at ? formatDateTime(b.paid_at) : '',
      b.checked_in_at ? formatDateTime(b.checked_in_at) : '',
      b.taler_handed_out_at ? formatDateTime(b.taler_handed_out_at) : '',
      b.cancelled_at ? formatDateTime(b.cancelled_at) : '',
      b.cancel_reason,
    ]),
  );
}
